# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Selfhosted Runner Link-to-QR CI

on:
  workflow_dispatch:

jobs:

  go_ci_job:
    name: Go CI Job
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go CI code Lint
      uses: golangci/golangci-lint-action@v3

    - name: Go CI code Unit Test
      run: go test -v ./...
      
    - name: Run Go Build
      run: go build -v ./...

    - name: Setup docker
      uses: docker/setup-buildx-action@v2.7.0
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/linktoqr
  
    - name: Docker Build and Push
      uses: docker/build-push-action@v4.1.1
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/linktoqr:latest 
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/linktoqr:latest, ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64,linux/arm/v8
